### ISSUE TITLE
is it possible to merge into the original repo ?

### ISSUE THREAD

**Issue by Samurais** [crownpku/rasa_nlu_chi#10]
hi, 
great to get your efforts to enable rasa_nlu with Chinese. It would be better if these changes are merged into https://github.com/RasaHQ/rasa_nlu.

**Comment by crownpku** [comment]
Hi @Samurais ,
I did try to merge to rasa_nlu, see pull request below:
https://github.com/RasaHQ/rasa_nlu/pull/477

The original code still has some issues having each component specify the languages it supports.
