### ISSUE TITLE
Error when demo data entity does not match tokenized result

### ISSUE THREAD

**Issue by crownpku** [crownpku/rasa_nlu_chi#2]
Error when demo data entity does not match tokenized result
For example, add "火锅" into entity example.
However, tokenized result is "吃火锅", then there is error.

Should add tokenization check for demo data.

**Comment by crownpku** [comment]
Solution is to implement Jieba into training data generation.

**Comment by justsmoke** [comment]
IMHO, this bug is due to wrong implementation of method 'tokenize' in jieba_tokenizer.py:
it should be Token(text, start_offset), rather than Token(text, length)

**Comment by crownpku** [comment]
@justsmoke Is it line 55  in rasa_nlu/tokenizers/jieba_tokenizer.py your are talking about?
```
tokens.append(Token(word, word_offset))
```

**Comment by justsmoke** [comment]
@crownpku yes

**Comment by crownpku** [comment]
Do you mind opening a pull request for fixing this bug? Thank you :)

**Comment by crownpku** [comment]
Thanks to @justsmoke for fixing the bug.
