### ISSUE TITLE
新增加的yaha不支持python3，无法正常启动服务。

### ISSUE THREAD

**Issue by luolitao** [crownpku/Rasa_NLU_Chi#25]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):

**Issue**:

**Content of configuration file** (if used & relevant):
```json

```

**Comment by crownpku** [comment]
建议先使用结巴分词的版本

**Comment by nacyzhaomin** [comment]
请问结巴分词的版本是哪个，谢谢

**Comment by luolitao** [comment]
自己修改文件，去掉与yaha有关的配置即可
