### ISSUE TITLE
乱码了怎么办？

### ISSUE THREAD

**Issue by safiindeed** [crownpku/Rasa_NLU_Chi#42]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):
`mitie`, `spacy_sklearn`
**Operating system** (windows, osx, ...):
linux
**Issue**:
中文不能正常显示
{
    "entities": [
        {
            "end": 3,
            "entity": "disease",
            "extractor": "ner_mitie",
            "start": 1,
            "value": "\u53d1\u70e7"
        }
    ],
    "intent": {
        "confidence": 0.5544729787361836,
        "name": "medical"
    },
    "intent_ranking": [
        {
            "confidence": 0.5544729787361836,
            "name": "medical"
        },
        {
            "confidence": 0.14118447377605906,
            "name": "affirm"
        },
        {
            "confidence": 0.1271251858682881,
            "name": "restaurant_search"
        },
        {
            "confidence": 0.10487447193717363,
            "name": "goodbye"
        },
        {
            "confidence": 0.07234288968229556,
            "name": "greet"
        }
    ],
    "text": "\u6211\u53d1\u70e7\u4e86\u8be5\u5403\u4ec0\u4e48\u836f\uff1f"
}

**Content of configuration file** (if used & relevant):
```json

```

**Comment by psfr937** [comment]
我都有这个问题，可以说你怎様解决吗？
