### ISSUE TITLE
How to generate example file?

### ISSUE THREAD

**Issue by Elfsong** [crownpku/rasa_nlu_chi#6]
**rasa NLU version** : 0.7.3

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...): [“nlp_mitie”, “tokenizer_jieba”, “ner_mitie”, “ner_synonyms”, “intent_featurizer_mitie”, “intent_classifier_sklearn”]

**Operating system**:  Centos

**Issue**:
Should I have to generate example json file(e.g. "data/examples/rasa/demo-rasa_zh.json") by manual?

**Content of configuration file** (if used & relevant):
```json

```

**Comment by crownpku** [comment]
Yes, this json file is for training your own NLU model, so you have to generate as much data as possible in it.

**Comment by Elfsong** [comment]
I see, thanks.
