### ISSUE TITLE
MITIE在本项目中的用途是什么

### ISSUE THREAD

**Issue by GaoQ1** [crownpku/Rasa_NLU_Chi#62]
**Rasa NLU version**:

**Operating system** (windows, osx, ...):

**Content of model configuration file**:
```yml

```

**Issue**:
首先谢谢作者的贡献。但最近这点没想通，MITIE在这个项目中是用来干嘛的，只是做word embedding吗？

**Comment by crownpku** [comment]
是的

**Comment by GaoQ1** [comment]
谢谢，还有一个问题，如果我想导入自己训练好的NER模型，这块应该如何做？

**Comment by yzho0907** [comment]
@GaoQ1 在/rasa_nlu/extractors/增加你自己的代码就好，同时替换models下比如entity_extractor.dat模型文件

**Comment by GaoQ1** [comment]
谢谢，我已经解决了
