### ISSUE TITLE
"error": "No project found with name 'default'."

### ISSUE THREAD

**Issue by yufengzhixing** [crownpku/rasa_nlu_chi#7]
rasa NLU version (e.g. 0.9.2):
0.9.2
Used backend / pipeline (mitie, spacy_sklearn, ...):
MITIE+Jieba+sklearn
Operating system (windows, osx, ...):
Ubuntu14.04
Issue:"error": "No project found with name 'default'."
username@linux:~$ curl -XPOST localhost:5000/parse -d '{"q":"下次见"}' | python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    67    0    50  100    17   8161   2775 --:--:-- --:--:-- --:--:--  8333
{
    "error": "No project found with name 'default'."
}
username@linux:~$ curl -XPOST localhost:5000/parse -d '{"q":"我胃痛，该吃什么药"}' | python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    85    0    50  100    35   8140   5698 --:--:-- --:--:-- --:--:--  8333
{
    "error": "No project found with name 'default'."
}
我进行到了最后一步测试过程中无预测结果，总是报错，报错如上文所示，请问是什么原因。如果您能抽空帮我看看将会非常感谢！

**Comment by crownpku** [comment]
训练完模型后，启动server请直接跑：
```
python -m rasa_nlu.server -c sample_configs/config_jieba_mitie_sklearn.json
```
会默认使用最新训练的模型。
先不要用`-p`来指定模型，否则会出现错误。

原因是因为最新的rasa_nlu需要在curl时指定project_name. 我正在更新一个新的config sample，稍后push上来。
