### ISSUE TITLE
意图识别

### ISSUE THREAD

**Issue by red-frog** [crownpku/Rasa_NLU_Chi#87]
**Rasa NLU version**:
0.14.4
**Operating system** (windows, osx, ...):
ubuntu 16.04

**Issue**:

比如说， 是的

可能的对话：
bot：你肚子疼吗？
user：是的
bot：你有呕吐现象吗？
user：是的

那么这两个  “是的”，是对不同问题的确认的一个描述，假如服务这边需要对每个情况做个slot填充， 这块怎么做呢？

**Comment by xxllp** [comment]
这是两个意图吧

**Comment by red-frog** [comment]
通过formaction解决了这个问题，https://github.com/RasaHQ/rasa_nlu/issues/1190
