### ISSUE TITLE
unwork on windows + pycharm + python3

### ISSUE THREAD

**Issue by glacierck** [crownpku/Rasa_NLU_Chi#9]
rasa NLU version (e.g. 0.9.2):
0.10.0a5
Used backend / pipeline (mitie, spacy_sklearn, ...):
MITIE+Jieba+sklearn
Operating system (windows, osx, ...):
windows
Issue:
E:\PychatmProjects\rasa_nlu_chi>pip install sklearn
Collecting sklearn
  Downloading http://mirrors.aliyun.com/pypi/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz
Requirement already satisfied: scikit-learn in d:\program files\python36\lib\site-packages (from sklearn)
Installing collected packages: sklearn
  Running setup.py install for sklearn ... done
Successfully installed sklearn-0.0

E:\PychatmProjects\rasa_nlu_chi>python -m rasa_nlu.train -c sample_configs/config_jieba_mitie_sklearn.json
INFO:rasa_nlu.components:Couldn't read dev-requirements.txt. Error: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\PychatmProjects\rasa_nlu_chi\rasa_nlu\train.py", line 116, in <module>
    do_train(config)
  File "E:\PychatmProjects\rasa_nlu_chi\rasa_nlu\train.py", line 104, in do_train
    trainer = Trainer(config, component_builder)
  File "E:\PychatmProjects\rasa_nlu_chi\rasa_nlu\model.py", line 120, in __init__
    components.validate_requirements(config.pipeline)
  File "E:\PychatmProjects\rasa_nlu_chi\rasa_nlu\components.py", line 96, in validate_requirements
    "Please install {}".format(", ".join(failed_imports)))
Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install sklearn, mitie

**Comment by crownpku** [comment]
Did you also install MITIE?

**Comment by glacierck** [comment]
y,Have already completed it.
(⊙o⊙)
git clone https://github.com/mit-nlp/MITIE.git
..
...
....
cmake --build . --config Release

**Comment by crownpku** [comment]
It seems strange that your sklearn is version 0.0...

Try run the following command to install all the required packages:
```
pip install -r requirements.txt
```

**Comment by glacierck** [comment]
**pip install -r requirements.txt**
Installing collected packages: rasa-nlu
  Found existing installation: rasa-nlu 0.10.0
    Uninstalling rasa-nlu-0.10.0:
      Successfully uninstalled rasa-nlu-0.10.0
  Running setup.py develop for rasa-nlu
Successfully installed rasa-nlu

**pip install git+https://github.com/mit-nlp/MITIE.git**
E:\workspace\rasa_nlu>pip install git+https://github.com/mit-nlp/MITIE.git
Collecting git+https://github.com/mit-nlp/MITIE.git
  Cloning https://github.com/mit-nlp/MITIE.git to c:\users\ck\appdata\local\temp\pip-k79ntbwq-build
Installing collected packages: mitie
  Running setup.py install for mitie ... error
Exception:
Traceback (most recent call last):
  File "d:\program files\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 24: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "d:\program files\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "d:\program files\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "d:\program files\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "d:\program files\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "d:\program files\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 24: invalid continuation byte

**Comment by glacierck** [comment]
**Okay. Here's how I got MITIE in Win10x64 working**

1. 
git clone https://github.com/mit-nlp/MITIE.git
2.
cd tools/ner_stream
mkdir build
cd build
cmake -G "Visual Studio 14 2015 Win64" ..
cmake --build . --config Release

back the top level MITIE folder

cd mitielib
mkdir build
cd build
cmake -G "Visual Studio 14 2015 Win64" ..
cmake --build . --config Release --target install
3.
 made a folder named 'mitie' in the Lib folder of python installation and copied  'MITIE/mitielib/*.*' all file
s  in it

**Comment by ddonano** [comment]
linux上也报错，“Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install mitie”，按照@glacierck的2、3步骤 安装了，好像没解决，这个工程对mitie有依赖吗

**Comment by ddonano** [comment]
搞定了，下载了mitie，执行 python setup.sh install 即可

**Comment by glacierck** [comment]
make sure MITIE

**Comment by lazyliang95** [comment]
> **pip install -r requirements.txt**
> Installing collected packages: rasa-nlu
> Found existing installation: rasa-nlu 0.10.0
> Uninstalling rasa-nlu-0.10.0:
> Successfully uninstalled rasa-nlu-0.10.0
> Running setup.py develop for rasa-nlu
> Successfully installed rasa-nlu
> 
> **pip install git+https://github.com/mit-nlp/MITIE.git**
> E:\workspace\rasa_nlu>pip install git+https://github.com/mit-nlp/MITIE.git
> Collecting git+https://github.com/mit-nlp/MITIE.git
> Cloning https://github.com/mit-nlp/MITIE.git to c:\users\ck\appdata\local\temp\pip-k79ntbwq-build
> Installing collected packages: mitie
> Running setup.py install for mitie ... error
> Exception:
> Traceback (most recent call last):
> File "d:\program files\python36\lib\site-packages\pip\compat__init__.py", line 73, in console_to_str
> return s.decode(sys.**stdout**.encoding)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 24: invalid continuation byte
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "d:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
> status = self.run(options, args)
> File "d:\program files\python36\lib\site-packages\pip\commands\install.py", line 342, in run
> prefix=options.prefix_path,
> File "d:\program files\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
> **kwargs
> File "d:\program files\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
> spinner=spinner,
> File "d:\program files\python36\lib\site-packages\pip\utils__init__.py", line 676, in call_subprocess
> line = console_to_str(proc.stdout.readline())
> File "d:\program files\python36\lib\site-packages\pip\compat__init__.py", line 75, in console_to_str
> return s.decode('utf_8')
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 24: invalid continuation byte

how did you solve this issue?
